osx_image: xcode8
language: objective-c

notifications:
  email: false

cache:
  directories:
  - Carthage

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35; bin/bootstrap-if-needed

script:
- xcodebuild clean build -project Trackers.xcodeproj -scheme Trackers-iOS -sdk iphonesimulator
- xcodebuild test -project Trackers.xcodeproj -scheme Trackers-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
- xcodebuild clean build -project Trackers.xcodeproj -scheme Trackers-Mac -sdk macosx
- xcodebuild test -project Trackers.xcodeproj -scheme Trackers-Mac -sdk macosx
